<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Panel
    |--------------------------------------------------------------------------
    */

    'new_users' => 'کاربران جدید',
    'user' => 'کاربر',
    'users' => 'کاربران',
    'followers' => 'دنبال کنندگان',
    'following' => 'دنبال شوندگان',
    'follow' => 'دنبال کردن',
    'unfollow' => 'لغو دنبال کردن',
    'webinars' => 'کلاس ها',
    'webinar' => 'کلاس',
    'webinar_sales' => 'فروش کلاس زنده',
    'content_sales' => 'فروش کلاس',
    'my_webinars' => 'کلاس های من',
    'you_not_have_any_webinar' => 'بدون کلاس!',
    'no_result_hint' => 'کلاس اول خود را ایجاد کنید و اجازه دهید دیگران از شما یاد بگیرند.',
    'choose_webinar' => 'یک کلاس را انتخاب کنید',
    'certificates' => 'گواهینامه ها',
    'quizzes' => 'آزمونها',
    'financial' => 'مالی',
    'requests' => 'درخواست ها',
    'support' => 'پشتیبانی',
    'send_new_support' => 'پیام پشتیبانی جدید',
    'notifications' => 'اطلاعیه',
    'settings' => 'تنظیمات',
    'log_out' => 'خروج',
    'create_a_class' => 'یک کلاس ایجاد کنید',
    'create_a_webinar' => 'یک کلاس ایجاد کنید',

    'invited_classes' => 'کلاسهای دعوت شده',
    'invited_teacher' => 'مربی دعوت شده',
    'invited_by' => 'دعوت شده توسط',
    'classes' => 'کلاس ها',
    'my_classes' => 'کلاس های من',
    'my_activity' => 'فعالیت من',
    'download_sales' => 'فروش را بارگیری کنید',
    'course_sales' => 'فروش کلاس',
    'only_not_conducted_webinars' => 'فقط کلاس های زنده برگزار نمی شود',
    'conducted' => 'انجام شده',
    'not_conducted' => 'انجام نشده است',

    'upcoming' => 'پیش رو',
    'start_learning' => 'شروع به یادگیری',
    'my_purchases_no_result' => 'کلاس خریداری نشده!',
    'my_purchases_no_result_hint' => 'یادگیری را از بهترین مربیان شروع کنید و لذت ببرید ...',

    'comment' => 'نطر',
    'comments' => 'نظرات',
    'reply' => 'پاسخ',
    'replied' => 'پاسخ داده شده',
    'not_replied' => 'پاسخ داده نشده',
    'report' => 'گزارش',
    'report_success' => 'گزارش شما ارسال شده است.',
    'report_fail' => 'گزارش ناموفق بود از ورود خود اطمینان حاصل کنید.',
    'new_comments' => 'نظرات جدید',
    'my_class_comments' => 'نظرات کلاس من',
    'my_comments' => 'نظرات من',
    'comments_statistics' => 'آمار نظرات',
    'filter_comments' => 'فیلتر کردن نظرات',
    'webinar_comments_list' => 'لیست نظرات کلاس',
    'comments_no_result' => 'شما هیچ نظری ندارید!',
    'comments_no_result_hint' => "وقتی دانش آموز در مورد کلاس های شما نظر می دهد \ و در این لیست ظاهر می شود.",
    'my_comments_no_result' => 'شما هیچ نظری ایجاد نکردید!',
    'my_comments_no_result_hint' => "نظرات شما به بهبود کیفیت جامعه کمک می کند ...",

    'my_purchases' => 'خریدهای من',
    'no_result_purchases' => 'کلاس خریداری نشده!',
    'no_result_purchases_hint' => 'یادگیری را از بهترین مربیان شروع کنید و لذت ببرید ...',
    'purchase_date' => 'تاریخ خرید',
    'purchased' => 'خریداری شده است',

    'favorites' => 'موارد دلخواه',
    'favorite' => 'مورد علاقه',
    'favorite_live_classes' => 'کلاسهای مورد علاقه',
    'no_result_favorites' => 'بدون کلاس مورد علاقه!',
    'no_result_favorites_hint' => 'می توانید یک کلاس به موارد دلخواه خود اضافه کنید و بعداً در آن ثبت نام کنید.',

    'meeting' => 'ملاقات',
    'meetings' => 'جلسات',
    'open_meetings' => 'جلسات باز',
    'pending_appointments' => 'جلسات در انتظار',
    'total_meetings' => 'مجموع جلسات',
    'amount' => 'مبلغ',
    'sales' => 'فروش ها',
    'sales_amount' => 'مبلغ فروش',
    'active_hours' => 'ساعت های فعال',
    'meeting_statistics' => 'آمار جلسات',
    'filter_meetings' => 'فیلتر کردن جلسات',
    'meeting_list' => 'لیست جلسات',
    'meeting_requests_list' => 'لیست درخواستهای جلسه',
    'show_only_open_meetings' => 'فقط جلسات باز را نمایش دهید',
    'create_link' => 'ایجاد پیوند',
    'contact_student' => 'تماس با دانش آموز',
    'contact_instructor' => 'تماس با مدرس',
    'finish_meeting' => 'پایان جلسه',
    'meeting_no_result' => 'بدون درخواست ملاقات!',
    'meeting_no_result_hint' => 'جلسات رزرو شده در این لیست نمایش داده می شود.',
    'student_contact_information' => 'اطلاعات تماس دانشجو',
    'instructor_contact_information' => 'اطلاعات تماس مربی',
    'my_timesheet' => 'برگه زمان من',
    'saturday' => 'شنبه',
    'sunday' => 'یکشنبه',
    'monday' => 'دوشنبه',
    'tuesday' => 'سه شنبه',
    'wednesday' => 'چهارشنبه',
    'thursday' => 'پنجشنبه',
    'friday' => 'جمعه',
    'join_live_meeting' => 'به جلسه زنده بپیوندید',
    'add_live_meeting_link' => 'پیوند جلسه زنده را اضافه کنید',
    'add_live_meeting_link_success' => 'پیوند جلسه زنده با موفقیت اضافه شد',
    'add_live_meeting_link_fail' => 'خطا در افزودن پیوند جلسه زنده',
    'add_live_meeting_link_hint' => 'می توانید از پیوندهای Zoom ، Bigbluebutton و غیره استفاده کنید',
    'url' => 'URL',
    'my_hourly_charge' => 'هزینه ساعتی',
    'number_only' => 'فقط اعداد ...',
    'temporary_disable_meetings' => 'غیر فعال کردن موقت جلسات',
    'success_temporary_disable_meetings' => 'جلسات با موفقیت غیرفعال شد.',
    'error_temporary_disable_meetings' => 'جلسات غیرفعال نشد.',
    'discount' => 'نرخ نزول',

    // dashboard
    'dashboard' => 'داشبورد',
    'i_not_available' => 'فعال کردن وضعیت آفلاین',
    'hi' => 'سلام ',
    'have_event' => 'شما دارید: رویدادهای جدید را بشمارید',
    'view_all_events' => 'مشاهده همه رویدادها',
    'account_balance' => 'موجودی حساب',
    'with_drawable' => 'قابل برداشت',
    'live_requests' => 'درخواستهای ملاقات',
    'monthly_sales' => 'فروش ماهانه',
    'learning_statistics' => 'یادگیری آمار',
    'support_messages' => 'پیام های پشتیبانی',
    'next_badge' => 'نشان بعدی',
    'noticeboard' => 'تابلو اعلانات',
    'noticeboards' => 'اعلامیه ها',
    'not_verified_alert' => 'هویت و اطلاعات مالی شما تأیید نشده است بنابراین ممکن است باعث تاخیر در روند پرداخت شود. لطفاً آنها را از',
    'this_link' => 'تنظیمات',
    // Conversations
    'conversations' => 'گفتگو',
    'create_support_message' => 'پیام پشتیبانی جدید',
    'course_support' => 'پشتیبانی کلاس',
    'course_type' => 'نوع کلاس',
    'platform_support' => 'پشتیبانی از پلت فرم',
    'department' => 'بخش',
    'attach' => 'پیوست',
    'attach_file' => 'فایل را ضمیمه کنید',
    'open_conversations' => 'باز کردن مکالمات',
    'closed_conversations' => 'گفتگوهای بسته',
    'total_conversations' => 'مجموع مکالمات',
    'messages_history' => 'تاریخچه پیام ها',
    'support_summary' => 'خلاصه پشتیبانی',
  	'classes_support' => 'پشتیبانی کلاس ها',
  	'support_tickets' => 'بلیط ها',
    'staff' => 'کارکنان',
    'teacher' => 'مدرس',
    'open' => 'باز',
    'closed' => 'بسته',
    'close_request' => 'بستن درخواست',
    'reply_to_the_conversation' => 'به مکالمه پاسخ دهید',
    'support_no_result' => 'شما پیام های پشتیبانی ندارید',
    'support_no_result_hint' => 'می توانید با مربیان و تیم پشتیبانی پلت فرم تماس بگیرید.',

    'select_support' => 'یک مکالمه را انتخاب کنید',
    'select_support_hint' => 'لطفاً یک مکالمه پشتیبانی را برای نمایش سابقه پیامها انتخاب کنید.',
    'message_filters' => 'فیلتر کردن پیام ها',

    // notifications
    'notification_no_result' => 'بدون اعلان',
    'notification_no_result_hint' => 'هر رویداد مهمی برای شما مورد توجه قرار خواهد گرفت ...',

    // comments
    'show_only_new_comments' => 'فقط نظرات جدید را نشان دهید',
    'reply_to_the_comment' => 'به کامنت پاسخ دهید',
    'edit_comment' => 'نظر را ویرایش کنید',

    //Marketing
    'marketing' => 'بازار یابی',
    'discounts' => 'تخفیفات',
    'create_a_new_discount' => 'تخفیف کلاس جدید',
    'create_a_new_special_offer' => 'یک پیشنهاد ویژه جدید ایجاد کنید',
    'show_only_active_discounts' => 'فقط تخفیف های فعال را نمایش دهید',
    'discount_no_result' => 'تخفیفی در کار نیست ...',
    'discount_no_result_hint' => 'می توانید تخفیف ایجاد کنید و فروش خود را افزایش دهید.',
    'special_offers_no_result' => 'بدون تخفیف...',
    'special_offers_no_result_hint' => 'می توانید تخفیف های کلاس اضافه کنید و فروش خود را افزایش دهید.',

    'promotion' => 'آفر ویژه',
    'promotions' => 'آفر های ویژه',
    'select_promotion_plan' => 'یک افر ویژه را انتخاب کنید',
    'promotions_history' => 'تاریخچه آفر ها',
    'promotion_days' => 'برای :day روز',
    'select_course' => 'یک کلاس را انتخاب کنید',
    'show_only_active_promotions' => 'فقط تبلیغات فعال را نمایش دهید',
    'popular' => 'محبوب',
    'plan' => 'طرح',
    'pay' => 'پرداخت',
    'expired' => 'منقضی شده',
    'promote_the_webinar' => 'کلاس را تبلیغ کنید',
    'select_webinar_for_promotion' => 'لطفاً کلاسی را که می خواهید تبلیغ کنید انتخاب کنید.',
    'promotion_no_result' => 'بدون تبلیغات!',
    'promotion_no_result_hint' => 'با فعال کردن برنامه های ارتقاء می توانید نمای کلاس و فروش خود را افزایش دهید.',

    // Instructors
    'filter_instructors' => 'مربیان فیلتر',
    'instructors_list' => 'لیست مدرسان',
    'add_an_instructor' => 'مربی جدید',
    'instructors_no_result' => 'هنوز مربی اضافه نشده است!',
    'instructors_no_result_hint' => 'می توانید مربیان مرتبط با سازمان ایجاد کنید.',

    'filter_students' => 'فیلتر دانش آموزان',
    'students_list' => 'لیست دانش آموزان',
    'add_an_student' => 'دانش آموز جدید',
    'students_no_result' => 'هنوز دانش آموزی اضافه نشده است!',
    'students_no_result_hint' => 'می توانید به راحتی دانش آموزان سازمان خود را اضافه کنید.',

    'meeting_sales' => 'فروش جلسات',
    'appointment_sales' => 'فروش جلسات',

    'bio' => 'بیوگرافی',
    'job_title' => 'عنوان شغلی',
    'bio_hint_1' => '"عنوان شغل" در پایین نام شما در کارت های نمایه نمایش داده می شود.',
    'bio_hint_2' => 'کوتاه (2 یا 3 کلمه) به عنوان مثال "طراح محصول ، مهندس ارشد نرم افزار".',
    'interests_hint_1' => 'انتخاب موضوعات مورد علاقه (برای مربیان) به دانش آموزان کمک می کند تا شما را برای جلسات زنده پیدا کنند.',
    'interests_hint_2' => 'اگر جلسات زنده برگزار می کنید ، موضوعات دقیق تری را انتخاب کنید.',
    'not_assign_any_webinar' => 'به هیچ کلاسی اختصاص داده نشده است',
    'active' => 'فعال',
    'inactive' => 'غیرفعال',
    'name' => 'نام',
    'special_offers' => 'پیشنهادهای ویژه',
    'special_offer' => 'پیشنهاد ویژه',
    'show_only_active_special_offers' => 'فقط پیشنهادات ویژه فعال را نمایش دهید',

    'offline_title' => 'فعال کردن وضعیت آفلاین',
    'offline_message' => 'پیام آفلاین',
    'offline_success' => 'وضعیت شما با موفقیت تغییر کرد!',
    'offline_hint' => 'اگر حساب خود را آفلاین قرار دهید ، پیامی در نمایه شما نمایش داده می شود و مورد توجه کاربران قرار می گیرد. می توانید یک پیام شخصی در ورودی زیر تایپ کنید.',

    // months
    'month_1' => 'Jan',
    'month_2' => 'Feb',
    'month_3' => 'Mar',
    'month_4' => 'Apr',
    'month_5' => 'May',
    'month_6' => 'Jun',
    'month_7' => 'Jul',
    'month_8' => 'Aug',
    'month_9' => 'Sep',
    'month_10' => 'Oct',
    'month_11' => 'Nov',
    'month_12' => 'Dec',

    'user_setting_success' => 'اطلاعات شما با موفقیت به روز شد',

    'remaining' => 'باقی مانده',

    'organization_classes' => 'کلاسهای سازماندهی',
    'filter_classes' => 'کلاس های فیلتر',
    'only_not_free_classes' => 'فقط کلاس رایگان نیست',
    'only_free_classes' => 'فقط کلاسهای رایگان',

    'new_noticeboard' => 'اطلاعیه جدید',
    'noticeboard_success_send' => 'اعلان جدید با موفقیت ارسال شد',
    'noticeboard_success_send_to' => 'تابلوی اعلانات جدید با موفقیت ارسال شد :users_count',

    'more_info' => 'اطلاعات بیشتر',
];
