<?php

return [

    /*
    |--------------------------------------------------------------------------
    | General Translations
    |--------------------------------------------------------------------------
    */

    'title' => 'عنوان',
    'sub_title' => 'عنوان فرعی',
    'name' => 'نام',
    'seo_description' => 'توضیحات متای SEO',
    'cover_image' => 'عکس روی جلد',
    'thumbnail_image' => 'بند انگشتی',
    'image' => 'تصویر',
  	'images' => 'تصاویر',
    'demo_video' => 'ویدئوی دمو',
    'optional' => 'اختیاری',
    'description' => 'توضیحات',
    'summary' => 'خلاصه',
    'study_time' => 'زمان مطالعه',
    'date_time' => 'تاریخ/زمان',
    'availability_times' => 'زمان های در دسترس بودن',
    'available' => 'در دسترس',
    'available_for_meetings' => 'Available for Meetings',
    'meeting' => 'جلسه',
    'meetings' => 'جلسات',
    'link' => 'لینک',
    'duration' => 'مدت زمان',
    'minutes' => 'دقیقه',
    'min' => 'دقیقه',
    'view' => 'بازدید',
    'view_profile' => 'مشاهده پروفایل',
    'review_or_edit' => 'بازبینی/ویرایش',
    'review' => 'بازبینی',
    'try_again' => 'دوباره امتحان کنید',
    'you_can_try_again' => 'نگران نباشید ، می توانید دوباره امتحان کنید.',
    'start' => 'شروع',
    'volume' => 'Volume',
    'file_type' => 'نوع فایل',
    'accessibility' => 'دسترسی',
    'choose_accessibility' => 'رایگان یا پولی؟',
    'attachments' => 'پیوست ها',
    'choose_attachments' => 'فایلهای مرتبط را به عنوان پیوست درس انتخاب کنید',
    'paid' => 'پرداخت شده',
    'paid_amount' => 'مبالغ پرداخت شده',
    'instructor' => 'مدرس',
    'instructors' => 'مدرسین',
    'students' => 'دانش اموزان',
    'students_and_instructors' => 'دانش آموزان و مربیان',
    'search_instructors' => 'جستجوی مربیان ...',
    'publish_date' => 'تاریخ انتشار',
    'forced' => 'اجباری',
    'yes' => 'بله',
    'no' => 'خیر',

    'course_sessions' => 'جلسات کلاس',
    'previous_lesson' => 'درس قبلی',
    'next_lesson' => 'درس بعدی',

    'drag_to_change_order' => 'برای تغییر ترتیب بکشید',

    'controls' => 'اقدامات',
    'phone' => 'موبایل',
    'mobile' => 'موبایل',
    'email' => 'ایمیل',

    'add_time' => 'اضافه کردن زمان',
    'clear_all' => 'همه را پاک کن',
    'additional_information' => 'اطلاعات تکمیلی',
    'capacity' => 'ظرفیت',
    'start_date' => 'تاریخ شروع',
    'time' => 'زمان',
    'date' => 'تاریخ',
    'date_created' => 'تاریخ ایجاد',
    'partner_instructor' => 'مربی همکار',
    'subscribe' => 'اشتراک  ',
    'add_to_cart' => 'افزودن به سبد خرید',
    'add_to_calendar' => 'افزودن به تقویم',
    'add_to' => 'اضافه کردن به',
    'reminder' => 'یادآور',
    'calendar' => 'تقویم',
    'price' => 'قیمت',
    '0_for_free' => '0 را برای رایگان وارد کنید',
    'free' => 'رایگان',
    'enroll_on_webinar' => 'ثبت نام در کلاس',
    'free_meetings' => 'جلسات رایگان',
    'select_a_partner_teacher' => 'مربی شریک را انتخاب کنید',
    'select_a_teacher' => 'یک مربی انتخاب کنید',
    'choose_instructor' => 'یک مربی انتخاب کنید',
    'search' => 'جستجو کردن',
    'search_instructor' => 'نام مربی ، ایمیل یا تلفن را جستجو کنید',
    'search_user' => 'کاربر را جستجو کنید',
    'tags' => 'تگ ها',
    'type_tag_name_and_press_enter' => 'نام برچسب را تایپ کرده و Enter را فشار دهید',
    'moderator_password' => 'رمز عبور مدیر',

    'category' => 'دسته بندی',
    'choose_category' => 'یک دسته را انتخاب کنید',
    'category_filters' => 'فیلترهای دسته بندی',
    'tickets' => 'تیکت ها',
    'add_ticket' => 'طرح جدید قیمت گذاری',
    'add_plan' => 'طرح جدید ',
    'add_new_ticket' => 'طرح جدید قیمت گذاری',
    'discount' => 'تخفیف',
    'ticket_no_result' => 'بدون طرح قیمت گذاری!',
    'ticket_no_result_hint' => 'با ایجاد برنامه های قیمت گذاری می توانید قیمت و زمان وابسته به ظرفیت را برای کلاس خود اضافه کنید.',

    'edit' => 'ویرایش',
    'delete' => 'حذف',
    'remove' => 'حذف',

    'list' => 'لیست',
    'reservation' => 'رزرو',
    'my_reservation' => 'رزروهای من',
    'result' => 'نتایج',
    'results' => 'نتایج',
    'my_results' => 'نتایج من',

    'all' => 'همه',
    'sessions' => 'جلسات',
    'add_session' => 'جلسه جدید',
    'add_new_sessions' => 'جلسه زنده جدید',
    'sessions_no_result' => 'جلسات زنده وجود ندارد!',
    'sessions_no_result_hint' => 'می توانید جلسات زنده ایجاد کنید تا دانش آموزان بتوانند به آن بپیوندند و شروع به یادگیری کنند.',
    'create_join_link' => 'ایجاد پیوند پیوستن',

    'newest' => 'جدیدترین',
    'expensive' => 'بالاترین قیمت',
    'inexpensive' => 'کمترین قیمت',
    'bestsellers' => 'پر فروشترین',
    'best_rates' => 'بیشترین امتیاز',

    'files' => 'فایل ها',
    'file' => 'فایل',
    'source' => 'منبع',
    'add_files' => 'فایل جدید',
    'add_new_files' => 'ایجاد فایل جدید',
    'files_no_result' => 'فایلی تعریف نشده است!',
    'files_no_result_hint' => 'شما می توانید قطعات ویدئویی دوره ، پروژه ها ، پیوست ها و تمرینات را به عنوان فایل تعریف کنید.',

    'test_lesson' => 'درس متن',
    'lesson' => 'درس',
    'add_test_lesson' => 'درس متن جدید',
    'add_new_test_lesson' => 'اضافه کردن درس متنی جدید',
    'text_lesson_no_result' => 'بدون درس متنی!',
    'text_lesson_no_result_hint' => 'دروس متنی ایجاد کنید تا دانش آموزان بتوانند در آنها ثبت نام کرده و شروع به یادگیری کنند.',

    'prerequisites' => 'پیش نیازها',
    'add_prerequisites' => 'پیش نیاز جدید',
    'add_new_prerequisites' => 'افزودن پیش نیاز جدید',
    'select_prerequisites' => 'انتخاب پیش نیاز ها',
    'search_prerequisites' => 'جستجوی پیش نیاز ها',
    'prerequisites_no_result' => 'هیچ پیش نیازی تعریف نشده است!',
    'prerequisites_no_result_hint' => 'شما می توانید پیش نیازهای اجباری یا پیشنهادی را برای یادگیری بهتر دانش آموزان ایجاد کنید.',

    'basic_information' => 'اطلاعات اولیه',
    'extra_information' => 'اطلاعات تکمیلی',
    'pricing' => 'قیمت گذاری',
    'content' => 'محتوا',

    'faq' => 'سوالات متداول',
    'add_faq' => 'سوال متداول جدید',
    'answer' => 'پاسخ',
    'answers' => 'پاسخ ها',
    'view_answers' => 'مشاهده پاسخ ها',
    'faq_no_result' => 'سوالات متداول تعریف نشده است!',
    'faq_no_result_hint' => 'با ایجاد سوالات متداول به کاربران کمک می کنید تا اطلاعات بیشتری در مورد کلاس شما کسب کنند.',

    'quiz_certificate' => 'آزمون و صدور گواهینامه',
    'certificate' => 'گواهی نامه',
    'certificate_id' => 'شناسنامه گواهینامه',
    'certificate_and_documents' => 'گواهینامه ها و اسناد',
    'add_quiz' => 'مسابقه جدید',
    'add_new_quizzes' => 'مسابقه جدید',
    'select_a_quiz' => 'یک آزمون را انتخاب کنید',
    'quiz' => 'آزمون',
    'questions' => 'سوالات',
    'total_mark' => 'Total Mark',
    'pass_mark' => 'Pass Mark',
    'mark' => 'Mark',
    'not_participated' => 'شرکت نکرده',
    'dont_have_quiz' => 'شما آزمونی ندارید ، لطفاً یک مسابقه تعریف کنید.',
    'quizzes_no_result' => 'هیچ آزمونی   برای این کلاس انتخاب نشده است.',
    'quizzes_no_result_hint' => 'با ایجاد آزمونها می توانید دانش آموزان را ارزیابی کرده و به آنها گواهینامه اعطا کنید.',

    'agree_rules' => 'با شرایط و ضوابط موافقم',

    'message_to_reviewer' => 'پیام به منتقد',

    'send_for_review' => 'ارسال برای بررسی',
    'save_as_draft' => 'ذخیره به عنوان پیش نویس',
    'draft' => 'پیش نویس',
    'waiting' => 'در انتظار',
    'done' => 'انجام شده',
    'reject' => 'رد کردن',
    'rejected' => 'رد شد',

    'close' => 'بستن',
    'save' => 'ذخیره',
    'continue' => 'ادامه',
    'submit' => 'ذخیره',
    'new' => 'جدید',
    'history' => 'تاریخچه',
    'item_id' => 'شناسه مورد',
    'export_list' => 'خروجی گرفتن از لیت دانش آموزان',
    'duplicate' => 'تکراری',

    'updated_at' => 'تاریخ به روز شده',
    'from' => 'از',
    'to' => 'به',
    'show_results' => 'نمایش نتایج',
    'status' => 'وضعیت',
    'published' => 'منتشر شده',
    'type' => 'نوع',
    'active' => 'فعال',
    'verified' => 'تأیید شده',
    'not_verified' => 'تایید نشده',
    'inactive' => 'غیرفعال',
    'disabled' => 'غیرفعال',
    'disable' => 'غیرفعال',
    'open' => 'بازکردن',
    'invoice' => 'صورتحساب',
    'feedback' => 'بازخورد',
    'by' => 'نوسط',
    'finish' => 'پایان',
    'finished' => 'پایان یافته',
    'pending' => 'در انتظار',
    'selected' => 'انتخاب شده',
    'select' => 'انتخاب',
    'required' => 'الزامی',
    'not_bought' => 'خریداری نشده!',
    'not_access' => 'دسترسی ممنوع!',
    'not_access_to_this_content' => 'Yشما به این محتوا دسترسی ندارید!',
    'play' => 'پخش',
    'play_online' => 'پخش (استریم)',
    'read' => 'خواندن',

    'are_you_sure' => 'مطمئنی؟',
    'deleteAlertHint' => "این عمل قابل انجام نیست!",
    'deleteAlertConfirm' => 'حذف',
    'deleteAlertFailHint' => 'خطا هنگام حذف مورد!',
    'deleteAlertSuccessHint' => 'مورد با موفقیت حذف شد.',
    'cancel' => 'لغو',
    'canceled' => 'لغو شده',
    'success' => 'موفق',
    'fail' => 'ناموفق',

    'unavailable' => 'غیر قابل دسترسی',
    'unavailable_description' => 'پیام عدم دسترسی',

    'not_defined' => 'تعریف نشده',

    'days' => 'روزها',
    'day' => 'روز',
    'hr' => 'ساعت',
    'sec' => 'ثانیه',
    'off' => 'Off',
    'offer' => ':off% آفر',

    'sort_by' => 'مرتب سازی بر اساس',
    'in' => 'در',
    'created_by' => 'ساخته شده توسط',
    'created_at' => 'تاریخ ایجاد شده',
    'created' => 'ایجاد شده',
    'create' => 'ایجاد کردن',
    'save_change' => 'ذخیره تغییرات',
    'ratings' => 'رتبه بندی ها',

    'share' => 'اشتراک گذاری',
    'share_this_course_with_others' => 'کلاس را با دوستان خود به اشتراک بگذارید',
    'profile' => 'مشخصات',
    'telegram' => 'تلگرام',
    'facebook' => 'فیس بوک',
    'whatsapp' => 'واتساپ',
    'twitter' => 'توییتر',
    'book_a_meeting' => 'یک جلسه رزرو کنید',
    'author_posts' => 'پست های نویسنده',
    'reserve_a_meeting' => 'رزرو جلسه',
    'go_to_class' => 'رفتن به کلاس',
    'go_to_settings' => 'به تنظیمات بروید',
    'course_page_title' => 'کلاس',

    'duplicate_review_for_webinar' => 'مرور تکراری برای کلاس',
    'creator' => 'ایجاد کننده',
    'manual' => 'راهنما',
    'automatic' => 'اتوماتیک',
    'start_payment' => 'شروع پرداخت',
    'pay' => 'پرداخت',
    'saturday' => 'شنبه',
    'sunday' => 'یکشنبه',
    'monday' => 'دوشنبه',
    'tuesday' => 'سه شنبه',
    'wednesday' => 'چهارشنبه',
    'thursday' => 'پنجشنبه',
    'friday' => 'جمعه',
    'all_days' => 'همه روزها',

    'my_panel' => 'پنل من',
    'my_profile' => 'پروفایل من',
    'user_profille_page_title' => 'مشخصات کاربر',
    'edit_selected_image' => 'برش تصویر انتخابی',

    'request_failed' => 'درخواست ناموفق بود',
    'request_success' => 'درخواست با موفقیت انجام شد!',

    'cart_page_title' => 'سبد خرید',
    'checkout_page_title' => 'ادامه خرید',
    'channel_payment_disabled' => 'درگاه پرداخت غیرفعال است.',
    'income_los_then_minimum_payout' => 'درآمد شما کمتر از حداقل مبلغ پرداختی است. لطفا منتظر بمانید تا محدودیت را تصویب کنید.',

    'paid_form_online_payment' => 'پرداخت آنلاین',
    'paid_form_credit' => 'اعتبار پرداخت شده',
    'paid_for_sale' => 'پرداخت برای فروش',
    'tax_get_form_buyer' => 'فرم مالیات خریدار',
    'income_sale' => 'فروش درآمد',
    'paid_for_commission' => 'برای کمیسیون پرداخت می شود',
    'get_commission_from_seller' => 'کمیسیون از فروشنده',
    'refund_money_to_buyer' => 'به خریدار مسترد می شود',
    'refund_tax' => 'مالیات مسترد شده',
    'refund_commission_to_seller' => 'بازپرداخت کمیسیون به فروشنده',
    'refund_commission' => 'کمیسیون بازپرداخت',
    'refund_income' => 'درآمد مسترد شده',
    'charge_account' => 'افزودن موجودی',
    'withdraw_account' => 'درخواست تسویه',
    'income_for_subscribe' => 'درآمد برای اشتراک',
    'paid_form_subscribe' => 'برای اشتراک پرداخت می شود',
    'income_for_promotion' => 'برای تبلیغات پرداخت می شود',

    'ticket_for_students_until_date' => 'برای اولین بار:students دانشجو تا :date ',
    'ticket_until_date' => 'تا :date',

    'about' => 'درباره',
    'educations' => 'تحصیلات',
    'experiences' => 'تجارب',
    'occupations' => 'مهارت ها',
    'identity_and_financial' => 'هویت و مالی',

    'copy' => 'کپی کردن',
    'copied' => 'کپی شده',
    'user_role' => 'نقش کاربر',
    'all_roles' => 'همه نقش ها',

    'error_404_page_title' => 'صفحه یافت نشد',
    'i_passed_this_lesson' => 'من این درس را گذراندم',
    'course_learning_change_status_success' => 'وضعیت یادگیری شما با موفقیت تغییر کرد.',
    'course_learning_change_status_error' => 'تغییر وضعیت یادگیری انجام نشد.',
    'course_learning_passed' => '  :percent%  درصد دوره گذرانده شده است.',

    'not_login_toast_lang' => 'محتوای محدود شده',
    'not_login_toast_msg_lang' => 'لطفاً برای دسترسی به محتوا وارد شوید.',
    'not_access_toast_lang' => 'دسترسی رد شد',
    'not_access_toast_msg_lang' => 'شما به این محتوا دسترسی ندارید.',
    'can_not_try_again_quiz_toast_lang' => 'دست دراز کرد',
    'can_not_try_again_quiz_toast_msg_lang' => 'نمی توانید دوباره این آزمون را انجام دهید.',
    'can_not_download_certificate_toast_lang' => 'دانلود نشد',
    'can_not_download_certificate_toast_msg_lang' => 'شما نمی توانید این گواهی را بارگیری کنید.',
    'session_finished_toast_title_lang' => 'جلسه به پایان رسید',
    'session_finished_toast_msg_lang' => 'خیلی دیر کردید ، این جلسه به پایان رسید.',

    'zoom_api' => 'Zoom API',
    'zoom_jwt_token' => 'Zoom JWT Token',
 	'how_zoom_jwt_token' => 'نحوه ایجاد توکن Zoom JWT',
    'instructor_is_not_available' => 'مربی موقتاً در دسترس نیست.',
];
