<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Admin Main Translation
    |--------------------------------------------------------------------------
    */

    'setting_and_profile' => 'تنظیم و نمایه',
    'setting' => 'تنظیمات',
    'settings' => 'تنظیمات',

    // seo
    'settings_seo_metas' => 'تنظیمات   seo',
    'seo_metas' => 'Seo metas',
    'seo_metas_home' => 'صفحه نخست',
    'seo_metas_search' => 'صفحه جستجو',
    'seo_metas_categories' => 'صفحه دسته بندی ها',
    'seo_metas_classes' => 'صفحه کلاس ها',
    'seo_metas_login' => 'صفحه ورود',
    'seo_metas_register' => 'صفحه ثبت نام',
    'seo_metas_about' => 'درباره صفحه',
    'seo_metas_contact' => 'صفحه تماس',
    'seo_metas_blog' => 'وبلاگ',
    'seo_metas_certificate_validation' => 'اعتبار گواهینامه',

    // socials
    'settings_socials' => 'تنظیمات اجتماعی',
    'socials' => 'شبکه های اجتماعی',

    // footer
    'settings_footer' => 'تنظیمات پاورقی',
    'footer' => 'پاورقی',
    'footer_first_column' => 'ستون اول',
    'footer_second_column' => 'ستون دوم',
    'footer_third_column' => 'ستون سوم',
    'footer_forth_column' => 'ستون چهارم',
    'item' => 'مورد',
    'item_title' => 'عنوان مورد',
    'item_link' => 'لینک مورد',

    // main
    'main' => 'اصلی',
    'home_sections' => 'قسمت اصلی',
    'settings_home_sections' => 'تنظیمات قسمت اصلی',
    'settings_main' => 'تنظیمات اصلی',
    'main_general' => 'عمومی',
    'site_name' => 'عنوان وب سایت',
    'site_email' => 'ایمیل وب سایت',
    'site_phone' => 'تلفن وب سایت',
    'site_language' => 'زبان سایت',
    'register_method' => 'روش ثبت نام',
    'user_languages_lists' => 'لیست زبان های کاربر',
    'rtl_languages' => 'زبانهای RTL',
    'fav_icon' => 'Fav icon',
    'fav_icon_placeholder' => 'نمایش در مرورگر (48*48 پیکسل)',
    'logo' => 'لوگو',
    'logo_placeholder' => 'نمایش روی سرصفحه (55*55 پیکسل)',
    'footer_logo' => 'لوگو فوتر',
    'footer_logo_placeholder' => 'نمایش روی سرصفحه (55*55 پیکسل)',
    'rtl_layout' => 'طرح RTL',
    'preloading' => 'بارگیری مجدد',

    'main_financial' => 'مالی',
    'courses_commission' => 'کمیسیون دوره ها',
    'tax' => 'مالیات',
    'minimum_payout_amount' => 'حداقل مبلغ پرداخت',

    'main_payment' => 'پرداخت',
    'currency' => 'واحد پول',
    'gateways' => 'دروازه ها',
    'gateway_paypal' => 'پی پال',
    'gateway_payu' => 'Payu',
    'gateway_paytm' => 'Paytm',
    'gateway_paystack' => 'Paystack',

    'main_home_hero' => 'Home hero section',
    'main_home_hero2' => 'Home hero section 2',
    'home_hero' => 'Home hero',
    'home_hero2' => 'Home hero 2',
    'background' => 'زمینه',
    'hero_background' => 'Hero زمینه',
    'hero_vector' => 'Hero vector',
    'has_lottie' => 'Has Lottie',

    'main_page_background' => 'Pages Background',
    'admin_login_background' => 'Admin login Background',
    'admin_dashboard_background' => 'Admin dashboard Background',
    'login_background' => 'Login Background',
    'register_background' => 'Register Background',
    'remember_pass_background' => 'Remember password Background',
    'verification_background' => 'Verification Background',
    'search_background' => 'Search Background',
    'categories_background' => 'Categories Background',
    'become_instructor_background' => 'Become instructor Background',
    'certificate_validation_background' => 'Certificate validation Background',
    'blog_background' => 'Blog Background',
    'instructors_background' => 'Instructors Background',
    'dashboard_background' => 'Dashboard Image',
    'panel_sidebar_background' => 'Panel sidebar Image',
    'user_avatar_background' => 'User default avatar',
    'user_cover_background' => 'User default Cover',

    'custom_css_js' => 'Custom css & js',
    'css' => 'Css',
    'js' => 'Js',

    'account_types' => 'انواع حساب',
    'add_account_types' => 'افزودن انواع حساب',

    'site_bank_accounts' => 'حسابهای بانکی سایت',
    'add_site_bank_accounts' => 'اضافه کردن حساب های بانکی',

    'report_reasons' => 'Report reasons',
    'add_report_reasons' => 'Add report reasons',

    'notifications' => 'اطلاعیه',
    'notification_admin' => 'مدیر',
    'notification_user' => 'کاربر',
    'notification_course' => 'دوره',
    'notification_financial' => 'مالی',
    'notification_sale_purchase' => 'فروش/خرید',
    'notification_plans' => 'برنامه ها',
    'notification_appointment' => 'وقت ملاقات',
    'notification_quiz' => 'آزمون',

    'notification_new_comment_admin' => 'new comment admin',
    'notification_support_message_admin' => 'support message admin',
    'notification_support_message_replied_admin' => 'support message replied admin',
    'notification_promotion_plan_admin' => 'promotion plan admin',
    'notification_new_contact_message' => 'new contact message',
    'notification_new_badge' => 'new badge',
    'notification_change_user_group' => 'change user group',
    'notification_course_created' => 'course created',
    'notification_course_approve' => 'course approve',
    'notification_course_reject' => 'course reject',
    'notification_new_comment' => 'new comment',
    'notification_support_message' => 'support message',
    'notification_support_message_replied' => 'support message replied',
    'notification_new_rating' => 'new rating',
    'notification_webinar_reminder' => 'webinar reminder',
    'notification_new_financial_document' => 'new financial document',
    'notification_payout_request_admin' => 'payout request admin',
    'notification_payout_request' => 'payout request',
    'notification_payout_proceed' => 'payout proceed',
    'notification_offline_payment_request' => 'offline payment request',
    'notification_offline_payment_approved' => 'offline payment approved',
    'notification_offline_payment_rejected' => 'offline payment rejected',
    'notification_new_sales' => 'new sales',
    'notification_new_purchase' => 'new purchase',
    'notification_new_subscribe_plan' => 'new subscribe plan',
    'notification_promotion_plan' => 'promotion plan',
    'notification_new_appointment' => 'new appointment',
    'notification_new_appointment_link' => 'new appointment link',
    'notification_appointment_reminder' => 'appointment reminder',
    'notification_meeting_finished' => 'meeting finished',
    'notification_new_certificate' => 'new certificate',
    'notification_waiting_quiz' => 'waiting quiz',
    'notification_waiting_quiz_result' => 'waiting quiz result',

    'contact_us' => 'Contact',
    'contact_us_edit' => 'Contact edit',
    'contact_us_address' => 'Contact address',
    'contact_us_phones' => 'Contact phones',
    'contact_us_emails' => 'Contact emails',
    'contact_us_background' => 'Contact page background',
    'map_position' => 'Map position',
    'map_zoom' => 'Map zoom',
    'map_position_latitude' => 'Map latitude',
    'map_position_longitude' => 'Map longitude',
    'contact_us_phones_placeholder' => 'Separate the numbers with ,',
    'contact_us_emails_placeholder' => 'Separate the emails with ,',

    'error_404' => '404 page',
    'error_404_image' => '404 Error image',
    'error_404_title' => '404 Error title',
    'error_404_description' => '404 Error description',

    'pages' => 'Pages',
    'new_page' => 'New page',
    'new_pages' => 'New Additonal Page',
    'edit_pages' => 'edit page ',
    'pages_name_placeholder' => 'page name in navbar',
    'pages_order_placeholder' => 'page order in navbar',
    'pages_lists_lead' => 'List of pages. You can edit or delete any row.',

    'latest_classes' => 'Latest classes',
    'best_sellers' => 'Best sellers',
    'free_classes' => 'Free classes',
    'discount_classes' => 'Discount classes',
    'best_rates' => 'Best rate classes',
    'trend_categories' => 'Trending categories section',
    'testimonials' => 'Testimonials section',
    'subscribes' => 'Subscribes section',
    'blog' => 'Blog section',
    'organizations' => 'Organizations section',
    'instructors' => 'Instructors section',
    'video_or_image_section' => 'Video or image section',
    'main_home_video_or_image_box' => 'Home page video or image section',

    'settings_navbar_links' => 'Navbar links settings',
    'navbar_links' => 'Navbar links',
    'top_navbar' => 'Top Navbar',
];
