<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Admin Users Translation
    |--------------------------------------------------------------------------
    */

    'users_list' => 'لیست کاربران',
    'user' => 'کاربر',
    'user_or_instructor' => 'کاربر یا مربی',
    'users' => 'کاربران',
    'classes' => 'کلاس ها',
    'classes_sales' => 'فروش کلاس ها',
    'purchased_classes' => 'کلاس های خریداری شده',
    'appointments' => 'Appointments',
    'appointments_sales' => 'Appointments Sales',
    'purchased_appointments' => 'Purchased Appointments',
    'wallet_charge' => 'شارژ کیف پول',
    'user_group' => 'گروه کاربر ',
    'action' => 'Action',
    'id' => 'ID',
    'name' => 'نام',
    'instructors' => 'مربی ها',
    'students' => 'دانش آموزان',
    'role_name' => 'عنوان نقش',
    'admin_role' => 'نقش مدیر',
    'full_name' => 'نام کامل',
    'status' => 'وضعیت',
    'users_count' => 'تعداد کاربر',
    'page_lists_lead' => 'لیست کاربران. می توانید هر سطری را ویرایش یا حذف کنید.',
    'new_page_lead' => 'می توانید یک کاربر جدید ایجاد کنید.',
    'create_field_full_name_placeholder' => 'انتخاب یک نام',
    'select_role' => 'انتخاب یک نقش',
    'select_status' => 'انتخاب یک وضعیت',
    'create_field_email_placeholder' => 'مثال: m@m.m',

    'search_user_or_instructor' => 'کاربر یا مربی را جستجو کنید',

    /// admin users badges
    'select_badge' => 'نشان را انتخاب کنید',
    'badges' => 'نشان ها',
    'register_date' => 'تاریخ ثبت نام',
    'course_count' => 'تعداد دوره ها',
    'course_rate' => 'نرخ دوره',
    'sale_count' => 'تعداد فروش',
    'support_rate' => 'نرخ پشتیبانی',
    'condition' => 'وضعیت',
    'condition_register_date' => 'روز',
    'condition_course_count' => 'دوره ها',
    'condition_course_rate' => 'ستاره ها',
    'condition_sale_count' => 'فروش ها',
    'condition_support_rate' => 'نرخ فروش',

    'groups' => 'گروه ها',
    'group_name' => 'اسم گروه',
    'users_groups' => 'گروه های کاربران',
    'new_user_group' => 'گروه کاربری جدید',

    'admin_users' => 'کاربران',
    'admin_users_list' => 'لیست کاربران',
    'admin_users_create' => 'ساخت کاربران',
    'admin_users_edit' => 'ویرایش کابران',
    'admin_users_delete' => 'حذف کاربران',
    'admin_users_badges' => 'نشان کاربران',

    'edit_page_title' => 'ویرایش کاربر ',
    'custom_badges' => 'نشان های اختصاصی',
    'auto_badges' => 'نشان خودکار',

    'supports' => 'پشتیبانی',
    'department' => 'بخش',
  	'support_depatments' => 'دپارتمان پشتیبانی',
    'new_department' => 'دپارتمان جدید',
    'edit_department' => 'ویرایش دپارتمان',
    'departments' => 'دپارتمان ها',

    'classes_conversations' => 'مکالمات کلاس',
    'course_conversations' => 'مکالمات کلاس',
    'course_conversations_lists_lead' => 'لیست مکالمات کاربران و مربیان',
    'support_conversation' => 'مکالمات پشتیبانی',
    'support_lists_lead' => 'لیست مکالمات پشتیبانی کاربر',
    'close_conversation' => 'بستن مکالمه',
    'open_attach' => 'بازکردن ضمیمه',
    'send_message_to' => 'ارسال پیام برای ',
    'send_message_to_teacher' => 'ارسال پیام برای مربی',

    'user_avatar' => 'آواتار کاربر',
    'user_name' => 'نام کاربر',
    'user_bio' => 'بیوگرافی کاربر',
    'rate' => 'نرخ',

    //new template notification
    'notifications' => 'اطلاعیه',
    'notification_single' => 'یک کاربر',
    'notification_all_users' => 'همه   کاربران',
    'notification_students' => 'همه   دانش آموزان',
    'notification_instructors' => 'همه   مربی ها',
    'notification_organizations' => 'همه سازمانها',
    'notification_group' => 'گروه خاص',
    'notification_students_and_instructors' => 'دانش آموزان و مربیان',
    'mark_all_read' => 'همه را به عنوان خوانده شده علامت بزن',
    'use_key_in_title_and_message_body' => 'می توانید از این کلیدها در عنوان و متن پیام استفاده کنید',

    'templates' => 'تمپلیت ها',
    'new_template' => 'تمپلیت جدید',
    'edit_template' => 'ویرایش تمپلیت',
    'email' => 'ایمیل کاربر',
    'mobile' => 'موبایل کاربر',
    'real_name' => 'نام کامل کاربر',
    'group_title' => 'عنوان گروه کاربر',
    'badge_title' => 'عنوان نشان',
    'financial_doc_desc' => 'شرح اسناد مالی',
    'financial_doc_type' => 'نوع سند مالی',
    'instructor_name' => 'نام مربی',
    'student_name' => 'نام دانش آموز',
    'course_title' => 'عنوان کلاس',
    'quiz_title' => 'عنوان آزمون',
    'quiz_result' => 'نتایج آزمون',
    'support_ticket_title' => 'عنوان تیکت پشتیبانی',
    'contact_us_title' => 'عنوان تماس با ما',
    'time_and_date' => 'زمان و تاریخ',
    'link' => 'لینک',
    'rate_count' => 'تعداد نرخ',
    'amount' => 'مبلغ',
    'payout_account' => 'حساب پرداخت',
    'subscribe_plan_name' => 'عنوان اشتراک',
    'promotion_plan_name' => 'عنوان پروموشن',
    // .\

    'reject_request' => 'رد درخواست',
    'become_instructor_info' => 'تبدیل شدن به اطلاعات مربی',
    'become_instructors' => 'مربی شدن',
    'instructor_requests' => 'درخواست های مربی',
    'accept_request' => 'پذیرش درخواست',
    'check_user_information' => 'بررسی اطلاعات کاربر',
    'become_instructors_list' => 'درخواست های مربی شدن',
    'become_instructors_lists_page_lead' => 'لیست درخواست های مربی شدن می توانید هر سطری را ویرایش یا حذف کنید.',

    'contacts' => 'مخاظبین',
    'contacts_lists' => 'پیام های مخاظبین',
    'contacts_message' => 'پیام های مخاظبین',

    'user_role_updated' => 'نقش کاربر تغییر کرد',
];
